2020-05-14 02:53:44,800 - teradata.udaexec - INFO - Initializing UdaExec...
2020-05-14 02:53:44,800 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/home/kamil/udaexec.ini: Not Found', '/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/udaexec.ini: Not Found']
2020-05-14 02:53:44,800 - teradata.udaexec - INFO - Found run number file: "/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/.runNumber"
2020-05-14 02:53:44,800 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2020-05-14 02:53:44,800 - teradata.udaexec - INFO - Removed 0 log files.
2020-05-14 02:53:44,817 - teradata.udaexec - INFO - Checkpoint file not found: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/SQL shell.checkpoint
2020-05-14 02:53:44,818 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2020-05-14 02:53:44,818 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: SQL shell
 *          Version: 1.0
 *       Run Number: 20200514025344-38
 *             Host: kamil-MS-7A34
 *         Platform: Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
 *          OS User: kamil
 *   Python Version: 3.6.9
 *  Python Compiler: GCC 8.4.0
 *     Python Build: ('default', 'Apr 18 2020 01:56:04')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: script.py
 *      Working Dir: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics
 *      Git Version: git version 2.17.1
 *     Git Revision: 181db07
 *        Git Dirty: True [ M libs/analysis/daily_usage.py, M libs/init_db.sql, M libs/samples.sql, M libs/utils.py, M script.py, M settings.json,?? .runNumber,?? logs/,?? sqls/]
 *          Log Dir: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/logs
 *         Log File: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/logs/SQL shell.20200514025344-38.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/home/kamil/udaexec.ini: Not Found', '/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=SQL shell;Version=1.0;JobID=20200514025344-38;ClientUser=kamil;Production=False;udaAppLogFile=/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/logs/SQL shell.20200514025344-38.log;gitRevision=181db07;gitDirty=True;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2020-05-14 02:53:44,820 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'system': '192.168.0.110', 'username': 'dbc', 'password': 'XXXXXX'}
2020-05-14 02:53:44,820 - teradata.tdodbc - INFO - Loading ODBC Library: /opt/teradata/client/ODBC_64/lib/libodbc.so
2020-05-14 02:53:44,824 - teradata.tdodbc - INFO - Available drivers: Teradata Database ODBC Driver 16.20, 
2020-05-14 02:53:44,966 - teradata.udaexec - INFO - Connection successful. Duration: 0.146 seconds. Details: {'method': 'odbc', 'system': '192.168.0.110', 'username': 'dbc', 'password': 'XXXXXX'}
2020-05-14 02:53:44,977 - teradata.udaexec - INFO - Query Successful. Duration: 0.010 seconds, Rows: 8, Query: SELECT TableName FROM DBC.TablesV WHERE TableKind = 'T' AND DataBaseName='movies'
2020-05-14 02:53:45,130 - teradata.udaexec - INFO - Query Successful. Duration: 0.148 seconds, Rows: 2, Query: SELECT DISTINCT CAST((calendar_date (FORMAT 'YYYY-mm-dd')) AS VARCHAR(10)) FROM Sys_Calendar.Calendar AS CALENDAR
LEFT OUTER JOIN 
(SELECT * FROM TDSP_ANALYSIS.daily_usage) AS MEASURES 
ON calendar_date = measure_date
WHERE calendar_date<=cast('2020-05-14' as DATE) 
AND calendar_date>=cast('2020-04-14' as DATE)
AND
(complete=0 OR complete IS NULL);
2020-05-14 02:53:45,192 - teradata.udaexec - INFO - Query Successful. Duration: 0.059 seconds, Rows: 24, Query: MERGE INTO TDSP_ANALYSIS.daily_usage as daily_usage USING
(

	SELECT CAST('2020-05-14' AS DATE) AS t_measure_date, 
	 SYSHOURS.HOUR_ID as t_measure_hour,
	 'movies' as t_table_name, 
     'movies' as t_database_name,
	 CASE 
	  	WHEN CAST('2020-05-14' AS DATE)<CURRENT_TIMESTAMP THEN 1
	 ELSE 0
	 END AS t_complete,
	 ZEROIFNULL(LOGS.TOTAL) as t_uses_total
	 FROM TDSP_ANALYSIS.system_hours AS SYSHOURS 
	LEFT OUTER JOIN 
	(
		SELECT EXTRACT(HOUR FROM CollectTimeStamp)
		AS "DHOUR", COUNT(QueryID) AS TOTAL FROM DBC.DBQLObjTbl 
		GROUP BY DHOUR
		WHERE LOWER(ObjectTableName)=LOWER('movies') 
		AND LOWER(ObjectDatabaseName)=LOWER('movies')
		AND CollectTimeStamp=CAST('2020-05-14' AS DATE)
	) AS LOGS ON DHOUR = HOUR_ID

) AS t_
ON measure_date=t_measure_date AND measure_hour=t_measure_hour AND table_name=t_table_name AND database_name=t_database_name

WHEN MATCHED THEN
	UPDATE SET complete=t_complete, uses_total=t_uses_total

WHEN NOT MATCHED THEN
	INSERT (measure_date, measure_hour, database_name, table_name, complete, uses_total)
	VALUES (t_measure_date, t_measure_hour, t_database_name, t_table_name, t_complete, t_uses_total);

2020-05-14 02:53:45,277 - teradata.udaexec - INFO - Query Successful. Duration: 0.084 seconds, Rows: 24, Query: MERGE INTO TDSP_ANALYSIS.daily_usage as daily_usage USING
(

	SELECT CAST('2020-05-13' AS DATE) AS t_measure_date, 
	 SYSHOURS.HOUR_ID as t_measure_hour,
	 'movies' as t_table_name, 
     'movies' as t_database_name,
	 CASE 
	  	WHEN CAST('2020-05-13' AS DATE)<CURRENT_TIMESTAMP THEN 1
	 ELSE 0
	 END AS t_complete,
	 ZEROIFNULL(LOGS.TOTAL) as t_uses_total
	 FROM TDSP_ANALYSIS.system_hours AS SYSHOURS 
	LEFT OUTER JOIN 
	(
		SELECT EXTRACT(HOUR FROM CollectTimeStamp)
		AS "DHOUR", COUNT(QueryID) AS TOTAL FROM DBC.DBQLObjTbl 
		GROUP BY DHOUR
		WHERE LOWER(ObjectTableName)=LOWER('movies') 
		AND LOWER(ObjectDatabaseName)=LOWER('movies')
		AND CollectTimeStamp=CAST('2020-05-13' AS DATE)
	) AS LOGS ON DHOUR = HOUR_ID

) AS t_
ON measure_date=t_measure_date AND measure_hour=t_measure_hour AND table_name=t_table_name AND database_name=t_database_name

WHEN MATCHED THEN
	UPDATE SET complete=t_complete, uses_total=t_uses_total

WHEN NOT MATCHED THEN
	INSERT (measure_date, measure_hour, database_name, table_name, complete, uses_total)
	VALUES (t_measure_date, t_measure_hour, t_database_name, t_table_name, t_complete, t_uses_total);

2020-05-14 02:53:45,286 - teradata.udaexec - ERROR - Query Failed! Duration: 0.008 seconds, Query: SELECT measure_hour,
sum(uses_total) as uses_total, 
AVG(uses_total) as avg_uses, 
MAX(uses_total) as max_uses 
FROM movies.daily_usage 
GROUP BY measure_hour
WHERE table_name='movies'
AND database_name='movies'
AND measure_date BETWEEN CAST('2020-04-14' AS DATE) AND CAST('2020-05-14' AS DATE)
ORDER BY measure_hour;
Traceback (most recent call last):
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/udaexec.py", line 790, in _execute
    func(query, params, **kwargs)
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/tdodbc.py", line 614, in execute
    checkStatus(rc, hStmt=self.hStmt, method="SQLExecDirectW")
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/tdodbc.py", line 231, in checkStatus
    raise DatabaseError(i[2], u"[{}] {}".format(i[0], msg), i[0])
teradata.api.DatabaseError: (3807, "[42S02] [Teradata][ODBC Teradata Driver][Teradata Database](-3807)Object 'movies.daily_usage' does not exist.")
2020-05-14 02:53:45,300 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/pandas/io/sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/udaexec.py", line 745, in execute
    self._execute(self.cursor.execute, query, params, **kwargs)
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/udaexec.py", line 790, in _execute
    func(query, params, **kwargs)
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/tdodbc.py", line 614, in execute
    checkStatus(rc, hStmt=self.hStmt, method="SQLExecDirectW")
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/teradata/tdodbc.py", line 231, in checkStatus
    raise DatabaseError(i[2], u"[{}] {}".format(i[0], msg), i[0])
teradata.api.DatabaseError: (3807, "[42S02] [Teradata][ODBC Teradata Driver][Teradata Database](-3807)Object 'movies.daily_usage' does not exist.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "script.py", line 86, in <module>
    results = new_one.read(runtime_settings["analysis"][an], runtime_settings["begin"], runtime_settings["end"])
  File "/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/libs/analysis/daily_usage.py", line 90, in read
    for hour_id in pd.read_sql(sSQL, self.connection).values:
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/pandas/io/sql.py", line 412, in read_sql
    chunksize=chunksize,
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/pandas/io/sql.py", line 1633, in read_query
    cursor = self.execute(*args)
  File "/home/kamil/Pulpit/Teradata/praca/pythonowe/virtualenv/teradata/lib/python3.6/site-packages/pandas/io/sql.py", line 1598, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT measure_hour,
sum(uses_total) as uses_total, 
AVG(uses_total) as avg_uses, 
MAX(uses_total) as max_uses 
FROM movies.daily_usage 
GROUP BY measure_hour
WHERE table_name='movies'
AND database_name='movies'
AND measure_date BETWEEN CAST('2020-04-14' AS DATE) AND CAST('2020-05-14' AS DATE)
ORDER BY measure_hour;': (3807, "[42S02] [Teradata][ODBC Teradata Driver][Teradata Database](-3807)Object 'movies.daily_usage' does not exist.")
2020-05-14 02:53:45,321 - teradata.udaexec - INFO - UdaExec exiting.
